### PR TITLE
Improve doc & table + fix build script

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by Chris00** [comment]
See also https://github.com/mirage/ocaml-cow/issues/100

**Comment by Chris00** [comment]
The build fails because `cowabloga` needs to be adapted.

**Comment by Chris00** [comment]
For the adaptation of `cowabloga` see https://github.com/mirage/cowabloga/pull/28

**Comment by samoht** [comment]
Thanks and sorry for the delay in merging this.

**Pull request merged**
