### PR TITLE
Remove all the syntax extensions, simplify build-system, remove camlp4

### PR DESCRIPTION
**Pull request by samoht**
Remove Code and Css too.

### CODE REVIEW

**Comment by samoht** [comment]
Don't merge yet, I need to see how bad this breaks mirage-www and cowabloga ...

**Comment by samoht** [comment]
This now has tests who pass, cowabloga is updated. Next step: mirage-www...

**Comment by chrismamo1** [comment]
@tbrk I've been toying with writing PPX versions of the COW syntax extensions, I might work on this more once my class schedule calms down.

**Comment by tbrk** [comment]
So, if I have read between the lines correctly, it seems that, globally, camlp4 is to be superseded by ppx, and it has thus been removed from ocaml-cow. Is that correct, @samoht?

I had understood from (Mirage OS wiki)[https://mirage.io/wiki/cow] that inline html was a core feature of ocaml-cow. It certainly works/ed very well. I made much use of this feature in an internal script to generate a shared website, but now it will stop working as soon as my team mates perform an opam update. I don't want to complain, just to explain the situation I find myself in.

@chrismamo1: of course, it would be great if there were an alternative that worked solidly and was available through opam.

I would try to contribute myself but I have too many other projects at the moment. I am just a grateful to benefit from the hard work behind ocaml-cow (before it stopped working!).

**Comment by samoht** [comment]
@tbrk yes camlp4 is deprecated and it is a pain to support both camlp4 and ppx so the priority was to have a camlp4-free code-base. You can still use older versions of cow if you want to keep using the camlp4 syntax extension (I do that for some of my website, using `opam pin add cow 1.4.0`)

There are now nicer alternative than `cow.syntax` (which was, to be honest a big hack) such as [tyxml](http://ocsigen.org/tyxml/3.6/api/Pa_tyxml) (a well-typed HTML syntax extension) and/or [markup.ml](http://aantron.github.io/markup.ml/) (an error-recovering HTML parser/serializer). 

@Drup what is a good source of documentation for tyxml syntax? Are you interested by updating/rewrinting https://mirage.io/wiki/cow with it?

**Comment by tbrk** [comment]
@samoht: OK. Thanks for the explanation and tips. I'll pin for now. Is the idea that ocaml-cow will eventually provide well-typed HTML inlining via ppx? Or is it better to migrate to tyxml?

**Comment by samoht** [comment]
I don't plan to add yet another ppx syntax for HTML myself, but I'm fine with accepting contributions if for any reason tyxml doesnt not fit with what users of CoW expect (or if users want a tighter integration with tyxml).

**Comment by Drup** [comment]
I'm in the middle of freshening tyxml up. Some documentation is now available [here](http://ocsigen.org/tyxml/dev/manual/intro). A ppx is actively being developed [here](https://github.com/ocsigen/tyxml/pull/89). The whole thing should (hopefully) land in opam in at most a week. I intend to provide various additional features too.

@samoht Do we really want to update this tutorial ? I never found it very good.

**Comment by samoht** [comment]
@Drup I'm fine to just delete it if in exchange I have a better tutorial for tyxml :p

**Comment by Drup** [comment]
> if in exchange I have a better tutorial for tyxml :p

If you don't think the new one is good enough, I would really like to know what I should improve!

**Comment by tbrk** [comment]
One last observation: the other feature that drew me to CoW in the first place was the tight integration of markdown, xml, and html into a single type (Xml.t). But maybe I can recover that in CoW/tyxml using the [functorial interface](http://ocsigen.org/tyxml/dev/manual/functors)?

**Comment by dsheets** [comment]
It's not clear to me why I, as a user, would adopt cow 2.0. What is gained from using it, now? Is it enough to justify the new dependency?

I think there is sufficient code existing that used the cow camlp4 syntax extension that if some libraries shift to cow 2.0 and some do not, they will be mutually uninstallable on a given opam switch.

Perhaps cow 2.0 could be something like `horse 1.0` as it seems the library is significantly different now?

**Comment by Drup** [comment]
@tbrk: The default implementation of tyxml (module `Html5` and `Svg`) are backed by a rather straightforward xml implementation `Xml`. The functorial implementation is if you want to use *another* Xml implementation (and I'll be happy to help if you want to do that).

**Comment by tbrk** [comment]
@Drup: OK. Thanks. I had the idea of using [dbuenzli/xmlm](https://github.com/dbuenzli/xmlm) for maximum compatibility with the Markdown module of CoW, but maybe that's all a bit heavy now just to use the [conversion code](https://github.com/mirage/ocaml-cow/blob/master/lib/markdown.ml#L21). I won't waste your time just yet; I'll have to think harder about everything!

**Comment by Drup** [comment]
@tbrk Iirc, xmlm is event based, it doesn't have an xml datatype.

**Comment by tbrk** [comment]
@Drup, maybe I'm mixed up somewhere, but I thought that [Xml.t in CoW](https://github.com/mirage/ocaml-cow/blob/master/lib/xml.ml#L19) was an xmlm [frag list](http://erratique.ch/software/xmlm/doc/Xmlm#TYPEfrag).

**Comment by tbrk** [comment]
@samoht: I finally had a chance to look back into all this. I converted my old scripts over to the new combinators (5e17206a0e7ec5e5592dd1c5f4a99a1f2061662e) and I agree that it looks pretty good. Thank you! The only tags I found missing were dl/dt/dd and it would be cool if ol/ul provided a way to set the child li classes (I'll submit a pull request if you want).

**Comment by samoht** [comment]
@tbrk a pull request would be very welcome, thanks!

**Comment by tbrk** [comment]
OK: #93 #94

**Pull request merged**
