### PR TITLE
Use a more efficient datastructure for entity → UTF-8 conversion

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by Chris00** [comment]
I did not see `xhtml.ml` before sending this.  I seem to have `vellip` that `xhtml.ml` doesn't.  Why is it not used in `xml`? (IIRC, XML entities have to be declared but it does not harm to decode them even if not, right?)

**Comment by Chris00** [comment]
BTW, is there any reason why you used escaped sequences?  And why an associative list instead of a more efficient structure?

**Comment by Chris00** [comment]
I modified the PR according to the above remarks.

**Comment by Chris00** [comment]
I thought the `Html.html_of_link` odd.  I added `Html.link` (from the signature of which it is obvious that one does not need to worry about proper escaping).

**Comment by samoht** [comment]
Thanks!

**Pull request merged**
