### PR TITLE
Add integrity and crossorigin attributes

### PR DESCRIPTION
**Pull request by tbrk**
See: https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes

### CODE REVIEW

**Comment by tbrk** [comment]
Hello @CraigFe and @avsm, what would you think about merging this patch? I've been using it for a while, it's quite useful for working with bootstrap.

**Comment by tbrk** [comment]
I'd still be interested in having this feature in the main branch and opam package if anyone has a cycle or two 😃.

**Comment by tbrk** [comment]
Great! Thanks @samoht!

**Comment by samoht** [comment]
Release here: https://github.com/ocaml/opam-repository/pull/24918

**Pull request merged**
